### ISSUE TITLE
Add additional person identifiers

### ISSUE THREAD

**Issue by mconlon17** [openrif/community#36]
Add additional person identifiers analogous to ORCiD and eRACommons:

Twitter username
LinkedIn username
Facebook username
Google username
ResearchGate username
Academia.edu username

**Comment by vioil** [comment]
this also should include addition of more IDs that are attached to a person in the institutional databases, like:
netID
employeeID
since most of institutions end up adding them in local ontology extensions. That should not be happening, the ontology should contain them.

These IDs should be sub-property of identifier, domain Person

**Comment by mconlon17** [comment]
Closing here.  Opening as https://github.com/openrif/vivo-isf-ontology/issues/703
